### ISSUE TITLE
Preparing Hackaton #6

### ISSUE THREAD

**Issue by da-ekchajzer** [Boavizta/boavizta-front#51]
# Project 

One of the projects of the next hackathon (Hackaton 6) would be to create a new tab in datavizta allowing to model the impacts of a server from its technical characteristics.

The objectives are multiple : 
* Use boaviztapi in a user-friendly way 
* Give a pedagogical tool to show the mutlicriteria and multistep impacts of a server
* Give an easy way to present and share our work on the API

This issue could detail the tasks that must be done during the hackathon to produce this tab. Here is a list of what I was thinking about. 

# TODO 

* [ ] create a navbar
* [ ] Create a new page, "impacts of a server"
* [ ] Create a form to characterize a server configuration (cpu, ram, ...)
* [ ] Create a form to characterize a server usage (location, consumption, workload, ...)
* [ ] Create a 
* [ ] Create a data visualization that report three types of impacts (gwp, pe, adp) on two lifecycle steps (manufacture and usage)

Please feel free to critic or comment on that. If you agree, I can give resources and detail some spec for each task in a specific issue.

**Comment by da-ekchajzer** [comment]
# Running the API

The API is stateless.

## Boaviztapi v0.2-alpha locally from repo

You can use the API locally be cloning the dev branch or by using the docker image.

Repo (dev) : https://github.com/Boavizta/boaviztapi/tree/dev

#### Prerequisite

Python 3, pipenv recommended

### Setup pipenv

Install pipenv globally

```bash
$ sudo pip3 install pipenv
```

Install dependencies and create a python virtual environment.

```bash
$ pipenv install -d 
$ pipenv shell
```

### Launch a development server

**Once in the pipenv environment**

Development server uses [uvicorn](https://www.uvicorn.org/) and [fastapi](https://fastapi.tiangolo.com/), you can launch development server with the `uvicorn` CLI.

```bash
$ uvicorn boaviztapi.main:app --host=localhost --port 5000
```

## Boaviztapi v0.2-alpha locally from docker image

Docker image : https://github.com/Boavizta/boaviztapi/pkgs/container/boaviztapi/43851962?tag=0.2.0a0

```bash
$ docker run ghcr.io/boavizta/boaviztapi:latest
```

## Boaviztapi v0.2-alpha hosted by Boavizta

You can use boaviztapi online .

**Endpoint : https://dev.api.boavizta.org**
